apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-deployment.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - storage.yaml
  - ingress.yaml
  - configmap.yaml 