apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Firebase configuration
  FIREBASE_PROJECT_ID: <base64-encoded-project-id>
  
  # Database configuration
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: <base64-encoded-password>
  DB_NAME: YXN0cm95YWFy
  
  # LLM API Keys
  OPENAI_API_KEY: <base64-encoded-openai-key>
  TAVILY_API_KEY: <base64-encoded-tavily-key>
  
  # Google Play configuration
  GOOGLE_PLAY_PACKAGE_NAME: Y29tLmFzdHJveWFhci5hcHA=
  GOOGLE_PLAY_SERVICE_ACCOUNT_JSON: L2FwcC9wdXJjaGFzZS1zZXJ2aWNlLWFjY291bnQuanNvbg==
  
  # AWS SES configuration
  AWS_ACCESS_KEY_ID: <base64-encoded-aws-access-key>
  AWS_SECRET_ACCESS_KEY: <base64-encoded-aws-secret-key>
  AWS_REGION: YXAtc291dGgtMQ==
  EMAIL_FROM: <base64-encoded-email>
  EMAIL_FROM_NAME: QXN0cm9ZYWFy