apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels:
    app: backend-api
data:
  DEBUG: "False"
  CORS_ORIGINS: '["https://astroyaar.co.in", "https://www.astroyaar.co.in"]'
  DATABASE_URL: "postgresql://postgres:postgres@metadata-db:5432/postgres"
  EMAIL_FROM: "info@astroyaar.co.in"
  EMAIL_FROM_NAME: "AstroYaar"
  AWS_REGION: "ap-south-1"
  DB_HOST: metadata-db
  DB_PORT: "5432"
  DB_USER: postgres
  DB_NAME: postgres
  REDIS_HOST: redis-cache
  REDIS_PORT: "6379"
  SE_EPHE_PATH: /app/ephe
  LOG_LEVEL: "INFO"
  ENV: "production" 