resources:
  - ../../base

patchesStrategicMerge:
  - configmap.yaml

patches:
  - target:
      kind: Deployment
      name: backend-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2 